language: python
sudo: false

script:
  - strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
  - strings /usr/lib/gcc/x86_64-linux-gnu/4.6/libstdc++.so | grep GLIBCXX
  - find / -name "*libstdc++.so*"
  - sh -c "$CMD"

matrix:
  fast_finish: true
  include:
    - env:
        - CMD="./mach test-tidy"
    - addons:
        apt:
          sources:
            #- ubuntu-toolchain-r-test
            - debian-sid
          packages:
            #- cmake
            - curl
            #- freeglut3-dev
            #- g++
            - git
            #- gperf
            #- libbz2-dev
            #- libfreetype6-dev
            #- libgl1-mesa-dri
            #- libglib2.0-dev
            #- libglu1-mesa-dev
            #- libosmesa6-dev
            #- libssl-dev
            - libstdc++6
            #- libstdc++6-dev
            #- libstdc++6-4.7-dev
            #- libxmu-dev
            #- libxmu6
            #- python-virtualenv
      env:
        - CMD="./mach build -d --verbose"

cache:
  directories:
    - $HOME/.cargo

branches:
  only:
    - master
