language: python
sudo: false

script:
  - sh -c "$CMD"

matrix:
  fast_finish: true
  include:
    - env:
        - CMD="./mach test-tidy"
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - debian-sid
          packages:
            - cmake
            - curl
            #- freeglut3-dev
            - g++-4.8
            - git
            #- gperf
            #- libbz2-dev
            #- libfreetype6-dev
            #- libgl1-mesa-dri
            #- libglib2.0-dev
            #- libglu1-mesa-dev
            #- libosmesa6-dev
            #- libssl-dev
            - libstdc++6
            #- libstdc++6-4.7-dev
            #- libxmu-dev
            #- libxmu6
            - python-virtualenv
      env:
        - CMD="./mach build -d --verbose"

cache:
  directories:
    - $HOME/.cargo

branches:
  only:
    - master
